version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - npm run export
  post_build:
    commands:
      - aws s3 sync out/ s3://taskplanner.pedroalvescloud
artifacts:
  files:
    - '**/*'